# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish dev image to Docker Hub

on:
  push:
    branches: ["main"]

env:
  USER_NAME: huolalatech
  IMAGE_NAME: page-spy-web

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --ignore-optional

      - name: Build
        run: |
          yarn run build:client
          cp -r dist backend/dist

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker hub image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Lark bot notify
        env:
          TOKEN: ${{ secrets.LARK_BOT_TOKEN }}
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          curl "https://pagespy.blucas.me/lark/ci?branch=$BRANCH_NAME&actionId=$GITHUB_RUN_ID" \
            -X POST \
            -H "token: $TOKEN"
